# Travis CI
## Link: https://travis-ci.org/iSCInc/extensions

sudo: false
language: node_js
node_js:
- 'stable'
- '4.0'
- '0.12'
cache:
  directories:
  - vendor/bundle
  - node_modules
script: gulp
install:
  - bundle install --deployment
  - npm install -g gulp
  - npm install
  - git submodule init
  - git submodule update
after_success:
  - tools/auto-deploy.sh
  - npm test
env:
  global:

## Gitter
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ef4324116ef803a6abf5
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: always     # options: [always|never|change] default: always
