sudo: false
language: node_js
node_js:
- '0.12'
cache:
  directories:
  - vendor/bundle
  - node_modules
install:
  - bundle install --deployment
  - npm install -g gulp
  - npm install
  - git submodule init
  - git submodule update
after_success:
  - tools/auto-deploy.sh
  - npm test
env:
  global:
